name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            mdexp-version: 0.0.20260814
            mdexp-digest: sha256:47e5646b2cd5bc802bfb776b1a110708195209ffbb6d9d2c274e368467842c15
          - os: macos-latest
            mdexp-version: 0.0.20260814
            mdexp-digest: sha256:facb30ccd73698cf52f07a8c3807cefe0b759022c99ebc86d6b13bb4288ce830

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install mdexp
        uses: ./setup-mdexp
        with:
          mdexp-version: ${{ matrix.mdexp-version }}
          mdexp-digest: ${{ matrix.mdexp-digest }}

      - name: Setup Dune
        # We review and manually update the action's commit used below.
        uses: mbarbin/setup-dune@03ede0220d3fe665f250727d8e21b7c0f9517f3b # v2.0.0+patch-7
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          version: "3.24.2"
          dune-digest: "sha256:3a9cac891f0b6086bfbf58d16c6c17ddfd1d493e031b6b43901f585a7f6899c7"
          workspace: "dune-workspace"
          cache-prefix: "build"
          cache-readonly: ${{ github.ref != 'refs/heads/main' }}
          steps: install-dune enable-pkg lazy-update-depexts install-gpatch install-depexts

      - name: Build & Run tests
        run: dune build @all @runtest
