name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install mdexp
        uses: ./setup-mdexp
        # As of the time of setting up this repo, there isn't any release of mdexp
        # available yet. We'll update the version below with the first one to use.
        with:
          mdexp-version: TBD
          mdexp-digest: sha256:TBD

      - name: Setup Dune
        # We review and manually update the action's commit used below.
        uses: mbarbin/setup-dune@ae2985bcdedc6fb24e5743d6f9dace9cf262b41c # v2.0.0+patch-4
        with:
          version: "3.21.0"
          steps: install-dune enable-pkg lazy-update-depexts install-gpatch install-depexts

      - name: Build & Run tests
        run: dune build @all @runtest
