name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install mdexp
        uses: ./setup-mdexp
        with:
          mdexp-version: TBD

      - name: Setup Dune
        # We review and manually update the action's commit used below.
        uses: mbarbin/setup-dune@1c4b81012f25bcff3ddc4cb2533cc8066802388f # v2.0.0+patched
        with:
          version: 3.20.2
          steps: install-dune enable-pkg lazy-update-depexts install-gpatch install-depexts

      - name: Build & Run tests
        run: dune build @all @runtest
