name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint shell scripts with shellcheck
        run: script/shellcheck.sh

      - name: Test local test script
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./setup-mdexp/test-install.sh \
            0.0.20260315 \
            sha256:f4fc53bcaa50c9dd979b968804c38322b9b7e6aa699d9d6d2d1f101965332018
