name: Create Release on Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: script/create-release.sh
