name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-setup-mdexp:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install mdexp using setup-mdexp action
        uses: ./setup-mdexp
        with:
          mdexp-version: TBD

      - name: Check mdexp version
        run: mdexp --version
